"""s commit

Revision ID: 27fd6655ab16
Revises: 23157d08baf8
Create Date: 2024-10-27 08:15:51.289460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27fd6655ab16'
down_revision: Union[str, None] = '23157d08baf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=320), nullable=False),
    sa.Column('owners', sa.ARRAY(sa.Integer()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('achivement')
    op.add_column('event', sa.Column('organizer', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'organizer')
    op.create_table('achivement',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='achivement_pkey')
    )
    op.drop_table('achievement')
    # ### end Alembic commands ###
