"""s commit

Revision ID: 3a5392f87dff
Revises: 8647413df25f
Create Date: 2024-10-26 15:56:17.348655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a5392f87dff'
down_revision: Union[str, None] = '8647413df25f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('events_management', sa.Boolean(), nullable=False))
    op.add_column('role', sa.Column('events_parttake', sa.Boolean(), nullable=False))
    op.add_column('role', sa.Column('roles_edit', sa.Boolean(), nullable=False))
    op.add_column('role', sa.Column('users_block', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('phone_number', sa.String(length=20), nullable=False))
    op.add_column('user', sa.Column('events', sa.ARRAY(sa.Integer()), nullable=True))
    op.alter_column('user', 'achievements',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.ARRAY(sa.Integer()),
               existing_nullable=True)
    op.create_index(op.f('ix_user_phone_number'), 'user', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_phone_number'), table_name='user')
    op.alter_column('user', 'achievements',
               existing_type=sa.ARRAY(sa.Integer()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.drop_column('user', 'events')
    op.drop_column('user', 'phone_number')
    op.drop_column('role', 'users_block')
    op.drop_column('role', 'roles_edit')
    op.drop_column('role', 'events_parttake')
    op.drop_column('role', 'events_management')
    # ### end Alembic commands ###
