"""s commit

Revision ID: 57a445d4124c
Revises: f7e72ac4ab3b
Create Date: 2024-10-26 15:58:46.724734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57a445d4124c'
down_revision: Union[str, None] = 'f7e72ac4ab3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('events_management', sa.Boolean(), nullable=False))
    op.add_column('role', sa.Column('events_parttake', sa.Boolean(), nullable=False))
    op.add_column('role', sa.Column('roles_edit', sa.Boolean(), nullable=False))
    op.add_column('role', sa.Column('users_block', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('phone_number', sa.String(length=20), nullable=False))
    op.add_column('user', sa.Column('events', sa.ARRAY(sa.Integer()), nullable=True))
    op.create_index(op.f('ix_user_phone_number'), 'user', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_phone_number'), table_name='user')
    op.drop_column('user', 'events')
    op.drop_column('user', 'phone_number')
    op.drop_column('role', 'users_block')
    op.drop_column('role', 'roles_edit')
    op.drop_column('role', 'events_parttake')
    op.drop_column('role', 'events_management')
    # ### end Alembic commands ###
