"""s commit

Revision ID: 764ce2091d49
Revises: aa8bc7756da7
Create Date: 2024-10-27 07:34:05.294110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '764ce2091d49'
down_revision: Union[str, None] = 'aa8bc7756da7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achivement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=320), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('achievement')
    op.drop_column('event', 'organizer')
    op.add_column('user', sa.Column('role', sa.String(), nullable=False))
    op.drop_column('user', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user', 'role')
    op.add_column('event', sa.Column('organizer', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_table('achievement',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.Column('owners', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='achievement_pkey')
    )
    op.drop_table('achivement')
    # ### end Alembic commands ###
