"""third commit

Revision ID: 94cf0649a774
Revises: f640d805f669
Create Date: 2024-10-25 18:59:34.582532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94cf0649a774'
down_revision: Union[str, None] = 'f640d805f669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('task', sa.Column('executor_id', sa.Integer(), nullable=False))
    op.add_column('task', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'role', ['role_id'], ['id'])
    op.drop_column('task', 'executor')
    op.drop_column('task', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('executor', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'role_id')
    op.drop_column('task', 'executor_id')
    op.drop_table('role')
    # ### end Alembic commands ###
