"""s commit

Revision ID: 9da04605528a
Revises: 8e2ca70168f1
Create Date: 2024-10-27 10:23:09.140159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da04605528a'
down_revision: Union[str, None] = '8e2ca70168f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement', sa.Column('title', sa.String(length=320), nullable=False))
    op.drop_constraint('achievement_name_key', 'achievement', type_='unique')
    op.create_unique_constraint(None, 'achievement', ['title'])
    op.drop_column('achievement', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement', sa.Column('name', sa.VARCHAR(length=320), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'achievement', type_='unique')
    op.create_unique_constraint('achievement_name_key', 'achievement', ['name'])
    op.drop_column('achievement', 'title')
    # ### end Alembic commands ###
