"""third commit

Revision ID: 9e044f983e94
Revises: 9e6ae64446a8
Create Date: 2024-10-25 19:07:52.882234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e044f983e94'
down_revision: Union[str, None] = '9e6ae64446a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('role')
    op.add_column('task', sa.Column('status_id', sa.Integer(), nullable=True))
    op.drop_constraint('task_role_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'status', ['status_id'], ['id'])
    op.drop_column('task', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_role_id_fkey', 'task', 'role', ['role_id'], ['id'])
    op.drop_column('task', 'status_id')
    op.create_table('role',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='role_pkey')
    )
    op.drop_table('status')
    # ### end Alembic commands ###
