"""Database

Revision ID: 9ef093a08f4c
Revises: b353ddab3e95
Create Date: 2024-10-26 17:36:32.068087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef093a08f4c'
down_revision: Union[str, None] = 'b353ddab3e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=320), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('performers', sa.ARRAY(sa.Integer()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('role', sa.Column('events_management', sa.Boolean(), nullable=False))
    op.add_column('role', sa.Column('events_parttake', sa.Boolean(), nullable=False))
    op.add_column('role', sa.Column('roles_edit', sa.Boolean(), nullable=False))
    op.add_column('role', sa.Column('users_block', sa.Boolean(), nullable=False))
    op.drop_constraint('user_role_id_fkey', 'user', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('user_role_id_fkey', 'user', 'role', ['role_id'], ['id'])
    op.drop_column('role', 'users_block')
    op.drop_column('role', 'roles_edit')
    op.drop_column('role', 'events_parttake')
    op.drop_column('role', 'events_management')
    op.drop_table('event')
    # ### end Alembic commands ###
